name: Deploy to GitHub Pages - Development
on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: 18.x
            - name: Install Dependencies
              run: npm install
            - name: Build Project
              run: VITE_BASE_URL=/react-ci-cd-testing/dev/ npm run build -- --mode development
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.REACT_CI_CD_TOKEN }}
                publish_dir: ./dist
                publish_branch: dev